name: CI tasks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Lint, Type check and Testings
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🚀 Build
        run: pnpm build

      - name: 👀 Lint
        run: pnpm lint:ci

      - name: 🧪 Test with coverage
        run: pnpm coverage

      - name: 📝 Upload coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
